triggers:
- envs: []
  name: Daily5AM
  pipeline_uuid: green_taxi_etl
  schedule_interval: 0 5 * * *
  schedule_type: time
  settings: {}
  sla: null
  start_time: 2024-02-01 05:00:00
  status: active
  variables: {}
